services:
  db:
    image: postgis/postgis:15-3.4
#    env_file:
#      - .env
    environment:
      POSTGRES_USER: ${APP__POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP__POSTGRES_PASSWORD}
      POSTGRES_DB: ${APP__POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 3

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: